//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDekho.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class car
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Specification { get; set; }
        public string Model { get; set; }
        public string Company { get; set; }
        [DisplayName("Upload File")]
        public string Photo { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
